### ISSUE TITLE
IndexError exceptions while labeling 

### ISSUE THREAD

**Issue by kemaleren** [ilastik/volumina#117]
While using the pixel classification workflow for labeling in a 3D volume, ilastik froze with two IndexError exceptions (included at the end of this issue).

I have reproduced this twice, but both times the error only happened after a long session of labeling.

Code versions:
- volumina: 9ff03856d0d12011405fe7353478a0ce034ed61c
- applet-workflows : d2faca5fe9695654762e6645800e2acf493bb62f
- lazyflow: f82aa162cbde44c8a97988ddda85bc8b9ae649ff
- widgets: cf61944b9e1651dd73e9a0f2c2f91488cd9e7895

```
Exception in thread Thread-60:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in
  __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/kemal/devel/ilastik-0.6/volumina/volumina/tiling.py",
  line 470, in _dirtyLayersWorker
    img = image_req.wait()
  File
  "/home/kemal/devel/ilastik-0.6/volumina/volumina/pixelpipeline/imagesources.py",
  line 131, in wait
    self._arrayreq.wait()
  File
  "/home/kemal/devel/ilastik-0.6/volumina/volumina/pixelpipeline/slicesources.py",
  line 22, in wait
    return self._sp(self._ar.wait())
  File
  "/home/kemal/devel/ilastik-0.6/volumina/volumina/slicingtools.py",
  line 190, in __call__
    projectedArray = domainArray[slicing]
IndexError: invalid index

Exception in thread Thread-61:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in
  __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/kemal/devel/ilastik-0.6/volumina/volumina/tiling.py",
  line 470, in _dirtyLayersWorker
    img = image_req.wait()
  File
  "/home/kemal/devel/ilastik-0.6/volumina/volumina/pixelpipeline/imagesources.py",
  line 274, in wait
    self._arrayreq.wait()
  File
  "/home/kemal/devel/ilastik-0.6/volumina/volumina/pixelpipeline/slicesources.py",
  line 22, in wait
    return self._sp(self._ar.wait())
  File
  "/home/kemal/devel/ilastik-0.6/volumina/volumina/slicingtools.py",
  line 190, in __call__
    projectedArray = domainArray[slicing]
IndexError: invalid index
```

**Comment by k-dominik** [comment]
I've not seen this error happening ever. Maybe we could close this, what do you think @akreshuk ?
