### ISSUE TITLE
Failing tests on OSX and Linux

### ISSUE THREAD

**Issue by chaubold** [ilastik/volumina#163]
While trying to build a binary right now (using latest ilastik/lazyflow/volumina masters as recorded in https://github.com/ilastik/ilastik-meta/commit/2ca2cf8b64c12886f1bf62e2362f442fced21ff9) I ran into these problems on both, OSX and Linux. I assume the first two are due to the switch to numpy 1.11, but I'm not sure about the others.

``` pytb
===== ilastik-everything-1.1.10a1.post4-0 OK =====
+ /bin/bash -x -e /Users/chaubold/opt/miniconda/conda-bld/test-tmp_dir/run_test.sh
+ set -e
+ cd /Users/chaubold/opt/miniconda/envs/_test/ilastik-meta/volumina/tests
+ nosetests .
......................Traceback (most recent call last):
  File "/Users/chaubold/opt/miniconda/envs/_test/ilastik-meta/volumina/tests/imagesources_test.py", line 60, in run
    run_old(*args, **kwargs)
  File "/Users/chaubold/opt/miniconda/envs/_test/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/chaubold/opt/miniconda/envs/_test/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 77, in _doNotify
    callback(result, **kwargs)
  File "/Users/chaubold/opt/miniconda/envs/_test/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 313, in _onNotify
    img = self.toImage()
  File "/Users/chaubold/opt/miniconda/envs/_test/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 294, in toImage
    d[:,:,0] *= self._tintColor.redF()
  File "/Users/chaubold/opt/miniconda/envs/_test/lib/python2.7/site-packages/numpy/ma/core.py", line 4057, in __imul__
    getdata(other)))
TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('uint32') with casting rule 'same_kind'

FAILURE: Uncaught exception in non-main thread during test: imagesources_test.AlphaModulatedImageSourceTest2.testRequest
E...Traceback (most recent call last):
  File "/Users/chaubold/opt/miniconda/envs/_test/ilastik-meta/volumina/tests/imagesources_test.py", line 60, in run
    run_old(*args, **kwargs)
  File "/Users/chaubold/opt/miniconda/envs/_test/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/chaubold/opt/miniconda/envs/_test/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 77, in _doNotify
    callback(result, **kwargs)
  File "/Users/chaubold/opt/miniconda/envs/_test/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 487, in _onNotify
    img = self.toImage()
  File "/Users/chaubold/opt/miniconda/envs/_test/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 450, in toImage
    a += 1
  File "/Users/chaubold/opt/miniconda/envs/_test/lib/python2.7/site-packages/numpy/ma/core.py", line 4025, in __iadd__
    getdata(other)))
TypeError: Cannot cast ufunc add output from dtype('int64') to dtype('uint8') with casting rule 'same_kind'

FAILURE: Uncaught exception in non-main thread during test: imagesources_test.ColortableImageSourceTest2.testRequest
E.........................
======================================================================
ERROR: testRequest (imagesources_test.AlphaModulatedImageSourceTest2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chaubold/opt/miniconda/envs/_test/ilastik-meta/volumina/tests/imagesources_test.py", line 99, in tearDown
    self.assertTrue( imagesources_thread_failures == 0 ) # Check for exceptions in other threads.
AssertionError: False is not true

======================================================================
ERROR: testRequest (imagesources_test.ColortableImageSourceTest2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chaubold/opt/miniconda/envs/_test/ilastik-meta/volumina/tests/imagesources_test.py", line 99, in tearDown
    self.assertTrue( imagesources_thread_failures == 0 ) # Check for exceptions in other threads.
AssertionError: False is not true

----------------------------------------------------------------------
Ran 52 tests in 9.274s

FAILED (errors=2)
TESTS FAILED: ilastik-everything-1.1.10a1.post4-0
```

**Comment by k-dominik** [comment]
hey @chaubold , is this still relevant?

**Comment by chaubold** [comment]
no, looks good now (tested on mac)
