### ISSUE TITLE
Scrolling out of range with swapped axes

### ISSUE THREAD

**Issue by akreshuk** [ilastik/volumina#173]
If you load 3D data, swap the original axes from zyx to xyz and then scroll to the end of the volume, the new limits are not registered and error messages about slicing position out of bounds start to pop:

```pytb
ERROR 2016-12-05 16:22:56,529 excepthooks 10595 139679365711680 Unhandled exception in thread: 'MainThread'
ERROR 2016-12-05 16:22:56,530 excepthooks 10595 139679365711680 Traceback (most recent call last):
  File "/home/akreshuk/miniconda2/envs/ilastik-devel-new/ilastik-meta/volumina/volumina/navigationController.py", line 355, in moveSlicingPosition
    self._updateSlice(self._model.slicingPos[i], i)
  File "/home/akreshuk/miniconda2/envs/ilastik-devel-new/ilastik-meta/volumina/volumina/navigationController.py", line 517, in _updateSlice
    raise Exception("NavigationController._setSlice(): invalid slice number = %d not in range [0,%d)" % (num, self._model.volumeExtent(axis)))
Exception: NavigationController._setSlice(): invalid slice number = 50 not in range [0,50)
```

**Comment by akreshuk** [comment]
Once the project has been saved, closed and then opened again it works fine though.

**Comment by akreshuk** [comment]
One more data point: it only happens in the Input Data applet, all the following applets are fine.
